version: '3.7'

services:
  api:
    build: ./api/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api/app/:/usr/src/app/
    ports:
      - 3011:8000
    env_file:
      - ./.env
    depends_on:
      - db

  ui:
    build: ./ui/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ui/app/:/usr/src/app/
    ports:
      - 3010:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db

volumes:
  postgres_data: